name: flutter_mobilshop
description: mobilshop
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  firebase_core: ^1.1.0
  cloud_firestore: ^1.0.7
  bloc_test: ^8.0.0
  mockito: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true